---
- name: Main playbook
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repository
      apt:
        update_cache: true
      changed_when: false
  
  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/cron.yml