---

- name: Test Ansible Pull
  hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Creating a file with content
    copy:
      dest: "/root/ok.txt"
      content: |
        hello
        world