---
- name: Main playbook
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repository
      apt:
        update_cache: true
      changed_when: false
  
  tasks:
    - include_tasks: 
        file: ./tasks/packages.yml